spring.application.name=UserRegistrationDemo

spring.r2dbc.url=${DATABASE_URL:r2dbc:postgresql://localhost:5432/postgres}
spring.r2dbc.username=${PGUSER:postgres}
spring.r2dbc.password=${PGPASSWORD:postgres}

external.email-service.url=${EXTERNAL_EMAIL_SERVICE_URL:https://example-email-service/api/send}
external.pdf-service.url=${EXTERNAL_PDF_SERVICE_URL:https://example-pdf-service/api/generate}
external.ip-geo-service.url=${EXTERNAL_IP_GEO_SERVICE_URL:http://ip-api.com/json}